### ISSUE TITLE
Session_name error after upgrade to 4.0

### ISSUE THREAD

**Issue by lynnfaraday** [mongoid/mongoid#4136]
I am trying to update my (non-Rails) Ruby app from Mongoid v3 to v4.

Old Gemfile:

    gem 'mongo', '~> 1.9.2'
    gem 'mongoid', '~> 3.1.6'

New Gemfile:

    gem 'mongo', '~> 2'
    gem 'mongoid', '~> 4.0.2'

I have made no other changes to the app besides changing the Gemfile and running bundle update/install.

Everything works fine with the old gem configuration. With the new one, each and every call to the database gives me the same error trying to get session_name.

Sample error from `MyModel.all.count`:

```
NoMethodError: undefined method `[]' for nil:NilClass
/Users/lynn/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/sessions/storage_options.rb:103:in `session_name'
/Users/lynn/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/sessions/thread_options.rb:10:in `session_name'
/Users/lynn/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/sessions/options.rb:100:in `session_name'
/Users/lynn/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/sessions.rb:105:in `mongo_session'
/Users/lynn/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/sessions.rb:121:in `collection'
/Users/lynn/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/sessions/options.rb:166:in `method_missing'
/Users/lynn/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:273:in `initialize'
/Users/lynn/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:53:in `new'
/Users/lynn/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:53:in `create_context'
/Users/lynn/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:35:in `context'
/Users/lynn/.rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:20:in `count'
```

Mongoid.yml:

```
development:
  sessions:
    default:
      database: mydb
      username: myuser
      password: mypassword
      hosts:
        - myhost:1234
      options:
```

FYI - my Ruby version is 2.2.1 using RVM.

I suspect it's a configuration issue, but I read the changelog but don't see anything different about the config file in v4. Any idea what I'm missing?
